### ISSUE TITLE
[BUG] Impossible to use regex and {kebab-case} for name in folder structure

### ISSUE THREAD

**Issue by jeannnemelanie** [Igorkowalski94/eslint-plugin-project-structure#25] opened 2024-12-03 22:12 UTC
I need to be able to catch all others children after the first children and also force kebab case to "all others children".

First I tried to do this:

```jsonc
{
  "rules": {
    "modules_folder": {
      "name": "modules",
      "children": [
        // First I declare the `custom-module` to apply the `custom_rule`
        {
          "name": "custom-module",
          "children": [{ "ruleId": "custom_rule" }]
        },
        // Then I tried to catch all other folders within `modules`
        // If I use `{kebab-case}` here, it overrides `custom-module` and
        // the `generic_rule` is applied to `custom-module` instead of `custom_rule`
        {
          "name": "{kebab-case}",  
          "ruleId": "generic_rule"
        }
      ]
    },
    "generic_rule": { /***/ },
    "custom_rule": { /***/ }
  }
}
```

Then:

```jsonc
{
  "rules": {
    "modules_folder": {
      "name": "modules",
      "children": [
        // First I declare the `custom-module` to apply the custom rule
        {
          "name": "custom-module",
          "children": [{ "ruleId": "custom_rule" }]
        },
        // Then I tried to catch all other folders within `modules`
        // If I use `"*"` here, the `custom_rule` is applied to `custom-module` as excepted
        // but all others children won't have to follow the `kebab-case` naming
        {
          "name": "*",  
          "ruleId": "generic_rule"
        }
      ]
    },
    "generic_rule": { /***/ },
    "custom_rule": { /***/ }
  }
}
```

I can't figure out if something is wrong in my setup or if it's just impossible to do it.

Thank you for your help.

**Comment by Igorkowalski94** [comment] 2024-12-03 23:40
Hi, could you paste an example of the entire folder structure you want to achieve? It will help me better understand what you're aiming for.

**Comment by Igorkowalski94** [comment] 2024-12-04 00:16
Hi, @jeannnemelanie I looked into the code and noticed an issue with the isRegex function, which was treating a string containing - as a regex. I believe that was the problem. Please update to version 3.10.7 and check if everything works correctly. If the issue persists, please send me the entire folder structure you want to achieve.

**Comment by jeannnemelanie** [comment] 2024-12-04 16:22
Hi @Igorkowalski94, thank you for your answer. I updated to 3.10.9 but the issue is still here.

I did a small sandbox to reduce the idea of the folder structure I try to work on: https://codesandbox.io/p/sandbox/black-fire-kxh57w.

Here is the code of the folder-structure.jsonc file:
```jsonc
{
    "$schema": "../node_modules/eslint-plugin-project-structure/folderStructure.schema.json",
    "structureRoot": "src",
    "structure": [{ "ruleId": "modules_root_folder" }],
    "rules": {
      /**
       * Root folder rules
       */
      "modules_root_folder": {
        "name": "modules",
        "children": [
          // grouped modules = custom behavior
          {
            "name": "(group|custom-group)(s)?",
            "children": [
              {
                "name": "{folder-name}-{kebab-case}",
                "ruleId": "module_with_tsx"
              }
            ]
          },
          // modules at root level = normal behavior
          // --> the issue is here if I use {kebab-case} for name
          { "name": "*", "ruleId": "module_with_tsx" }
        ]
      },
  
      /**
       * Module / submodule rules
       */
      "module_with_tsx": {
        "enforceExistence": ["index.ts"],
        "children": [
          // a module:
          // - should have an index.ts file
          // - can have his internal files (xxx.component.tsx, xxx.helper.ts, etc) with related tests files (xxx.component.test.tsx)
          // - can have sub-modules folders
          { "ruleId": "submodule_with_tsx" },
          { "name": "index.ts" },
          { "ruleId": "module_ts_files" },
          { "ruleId": "module_tsx_files" }
        ]
      },
      "submodule_with_tsx": {
        "name": "{folder-name}-{kebab-case}",
        "enforceExistence": ["index.ts"],
        "children": [
          // a sub-module:
          // - should have an index.ts file
          // - can have his internal files (xxx.component.tsx, xxx.helper.ts, etc) with related tests files (xxx.component.test.tsx)
          // - can not have folders
          { "name": "index.ts" },
          { "ruleId": "module_ts_files" },
          { "ruleId": "module_tsx_files" }
        ]
      },
  
      /**
       * Files rules
       */
      "module_ts_files": {
        "name": "{folder-name}.(constant|helper|hook|type)(.test)?.ts"
      },
      "module_tsx_files": {
        "name": "{folder-name}.(component|provider)(.test)?.tsx"
      }
    }
  }
  
```

**Comment by Igorkowalski94** [comment] 2024-12-04 17:03
I can already see what the problem is. 

You have two rules for folder names that meet the same condition `{kebab-case}`. In such cases, the [library automatically removes the duplicate](https://github.com/Igorkowalski94/eslint-plugin-project-structure/wiki/project%E2%80%91structure-%E2%80%8Bfolder%E2%80%91structure#children) and selects one of them. You need to write it like this:

```json
  "structureRoot": "src",
  "structure": [{ "ruleId": "modules_folder" }],
  "rules": {
    "modules_folder": {
      "name": "modules",
      "children": [
        { "name": "group", "ruleId": "group_folder" },
        { "name": "groups", "ruleId": "group_folder" },
        { "name": "custom-group", "ruleId": "group_folder" },
        { "name": "custom-groups", "ruleId": "group_folder" },
        { "ruleId": "module_folder" }
      ]
    },

    "group_folder": {
      "name": "group",
      "children": [
        { "name": "{folder-name}-{kebab-case}", "ruleId": "module_folder" }
      ]
    },

    "module_folder": {
      "name": "{kebab-case}",
      "children": [
        { "name": "{folder-name}-submodule", "ruleId": "module_folder" },
        { "name": "index.ts" },
        { "name": "{folder-name}.component.tsx" }
      ]
    }
  }
```

**Comment by Igorkowalski94** [comment] 2024-12-04 17:54
@jeannnemelanie  Let me know if everything is working as it should or if you have any further questions. If everything is working, please close the issue.

**Comment by jeannnemelanie** [comment] 2024-12-04 20:26
@Igorkowalski94 Ok understand! Thank you for both solutions. I'm going to test it and I'll let you know.

**Comment by jeannnemelanie** [comment] 2024-12-04 20:57
@Igorkowalski94 I picked the second solution and it works perfectly! 

I choosed the second solution because I have quite a lot of options in the group folder `(group|custom-group)(s)?`, so it would be a lot of different lines to declare with the first solution. I had a note to make sure the team will be careful about the rules order.

Thanks a lot for your help! 
Very usefull package by the way!

**Closed** 2024-12-04 21:24 UTC
Labels: bug

**Comment by Igorkowalski94** [comment] 2024-12-04 23:21
Hi @jeannnemelanie , as a bonus, I improved the sorting algorithm to make it more intuitive. 

It still sorts in the order of fixedNames -> Regex -> Regex with * -> *, but it no longer changes the internal order of data within a group.

So, in version 3.10.10, it will be saved like this:

```jsonc
{
    "modules_folder": {
      "name": "modules",
      "children": [
        { "ruleId": "group_folder_2" } // First
        { "ruleId": "module_folder" }, // Second 
      ]
    },
}
```

This is more intuitive because the group_folder rule is more specific and should intuitively be ranked higher.

**Comment by jeannnemelanie** [comment] 2024-12-06 16:11
Hi @Igorkowalski94 thanks a lot for the bonus! I did not have time yesterday to try it. But I'll give it a shop next week.

**Comment by jeannnemelanie** [comment] 2024-12-17 21:29
Hi @Igorkowalski94 just to let you know, I did the update and everything works great. Thank you!
